server:
  port: 9083

logging:
  level:
    root: INFO
    org.springframework.web: INFO

security:
  oauth2:
    client:
      client-id: serviceClient
      client-secret: secret
      grant-type: client_credentials
      access-token-uri: http://localhost:8080/auth-server/oauth/token
      user-authorization-uri: http://localhost:8080/auth-server/oauth/authorize

spring:
  main:
    allow-bean-definition-overriding: true