server:
  port: 8080

jasypt:
  encryptor:
    algorithm: PBEWITHSHA1ANDDESEDE
    keyObtentionIterations: 10000

jwt:
  key-store: /key/auth_store.jks
  store-pass: ENC(C9S/riFqH1Xm8GRSqZws7REooMNN1Tr9RvYY3vHBWf0=)
  key-alias: auth_store
