server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-server
          uri: http://localhost:9080/
          predicates:
            - Path=/oauth/**
