server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
          predicates:
            - Path="/"+serviceId+"/**"
          filters:
            - RewritePath="/"+serviceId+"/(?<remaining>.*)", "/${remaining}"
      routes:
        - id: resource-server
          uri: http://localhost:9081
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/