server:
  port: 9081

logging:
  level:
    root: INFO
    org.springframework.web: INFO

security:
  oauth2:
    resource:
      jwt:
        key-uri: http://localhost:9080/oauth/token_key

spring:
  application:
    name: resource-server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/