security:
  oauth2:
    client:
      client-id: resServer
      client-secret: secret
    resource:
      token-info-uri: http://localhost:8080/oauth/check_token

server:
  port: 9081
logging:
  level:
    root: INFO
    org.springframework.web: INFO      
      